module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_REPLY_STATUS: 'true',
    AUTO_CALL_CUT: 'true',
    AUTO_RECORDING: 'false',
    AUTO_TYPING: 'false',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💫', '🌟', '🎋', '🫀', '👀', '🤖', '🥰', '🗿', '💙', '🌝'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/GnYQAKjoW8QD0vZL5abDk7?mode=gi_t',
    IMAGE_PATH: 'https://i.ibb.co/QF4wSsPh/IMG-20251223-WA0415.jpg',
    NEWSLETTER_JID: '120363407047154010@newsletter',
    BOT_NAME: '🧛‍♂️ SO MINI MD 🧛‍♂️',
    OWNER_NAME: 'SHANUKA SHAMEEN',
    OWNER_NUMBER: '94724389699',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> *Powered By So Mini 🧛‍♂️🩸*',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbCMX3K7j6fxob6STf3C'
};