module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/GnYQAKjoW8QD0vZL5abDk7?mode=gi_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.ibb.co/QF4wSsPh/IMG-20251223-WA0415.jpg',
    NEWSLETTER_JID: '120363407047154010@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '🧛‍♂️ 𝕾𝕺 𝕸𝕯 🧛‍♂️',
    OWNER_NAME: 'Shanuka Shameen',
    OWNER_NUMBER: '94724389699',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> *𝐏ᴏᴡᴇʀᴅ 𝐁ʏ 𝐒ᴏ 𝐌ɪɴɪ 🧛‍♂️🩸*',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbCMX3K7j6fxob6STf3C',
};
